### ISSUE TITLE
CPU players are super dumb

### ISSUE THREAD

**Issue by Ant84** [PartyPlanner64/PartyPlanner64#32] opened 2016-11-10 20:09 UTC
They only go the same way all the time. in some cases its impossible to lose because they don't go to the star.I know this isn't partyplanners fault but can you guys maybe do some thing to fix this.

**Comment by PartyPlanner64** [comment] 2016-11-11 02:10
Closing as duplicate of Issue #17.

I kind of have an idea of where the AI data is, but I don't understand it yet. Basically every split in the path is hard coded with, I suspect, the choice that the AI should make in order to head towards the current star. It might be muddied with other considerations too. I could build out the AI data pretty easily if I just knew what the structure was.

**Closed by PartyPlanner64** 2016-11-11 02:10 UTC
Labels: duplicate
