### ISSUE TITLE
Issues overwriting marioparty 2 boards

### ISSUE THREAD

**Issue by somerandomgamer1** [PartyPlanner64/PartyPlanner64#88] opened 2020-03-24 02:49 UTC
For some reason, whenever I try to overwrite a marioparty 2 board with a custom board, I get a message saying that the board cannot be overwritten. I have followed every requirement as well, so I don't know what is wrong. 
Here is a picture of what I am describing:
![Annotation 2020-03-23 194845](https://user-images.githubusercontent.com/62578032/77383142-58e52180-6d3f-11ea-8dec-e3a12c2651d8.png)

**Comment by PartyPlanner64** [comment] 2020-04-05 22:52
I tried overwriting MP2 with Toy Dream recently and it seemed to work fine. Is there any particular board this is happening with?

There may be a more specific error in the browser console, accessed with F12.

**Comment by LogingCoolMario** [comment] 2020-04-14 15:14
I seem to be having the same problem but with Mario Party 1. I've tried to overwrite 4 different boards over DK's Jungle Adventure but I keep getting the same error as shown in OP's screenshot.

**Comment by PartyPlanner64** [comment] 2020-04-26 17:13
Mario Party 1 issue was definitely a problem, and has been fixed now.

Beyond that, I don't know of any other issues with other titles. I've made it so this error screen will show the actual error text, so if you can provide that, it will help with resolving this issue.

**Comment by PartyPlanner64** [comment] 2020-08-02 15:46
Closing issue due to unknown steps to reproduce. Please comment if the issue is still occurring.

**Closed by PartyPlanner64** 2020-08-02 15:46 UTC
Labels: needs information
