### ISSUE TITLE
Mario Party 3 Custom Boards dont work on Everdrive!!! *Crash* (Bug), Needs investigation imediately! (Please Solve this ploblem!)

### ISSUE THREAD

**Issue by JMGO-N64** [PartyPlanner64/PartyPlanner64#57] opened 2018-03-02 18:26 UTC
Mario Party 1 and 2 custom boards works great on Everdrive, but MP3 custom boards crash after the presentation of the board, why?, Is the Partyplanner 64 focused on running the games on emulators and not on real hardware?, I whould be so sad If this is true!, I've already made 20 MP1 Custom boards, 12 MP2 Custom boards Whit work great, but only 9 MP3 custom boards with all have crashed in the presentation of the board when i try to run it in my Everdrive 64 Plus!, Please solve this ploblem!, I Still waiting for Answers!!!!, I want to play my Mario Party 3 Custom boards on my Everdrive!!!!!

**Comment by PartyPlanner64** [comment] 2018-03-03 02:17
Well, I don't have an Everdrive, but I can try a MP3 board on 64drive and see if anything regressed there.

**Comment by PartyPlanner64** [comment] 2018-03-03 02:44
I tried Paradise Isles on 64drive and it was working fine.

Does the clean MP3 ROM work fine? Or is there special settings that Everdrive applies to only the clean ROM but it can't detect to do so for patched ROMs? I'm wondering most if it is set up to do 16K save types correctly.

**Comment by JMGO-N64** [comment] 2018-03-04 05:51
I dont know, but the clean MP3 rom Works fine, and even my modified MP2 and MP1 ROMs whit Partyplanner 64 Works great!, And whit no Crash or Bug, it's only the MP3 custom that crashs, i really dont know why this happens, Is it something with the maps, or is it because of Everdrive?, I really want to play my MP3 custom maps too, but really dont know what to do!

**Comment by JMGO-N64** [comment] 2018-03-05 14:15
If you want, I can send you my Custom Boards in Json file for you, maybe it helps to figure out what's causing the problem.

**Comment by PartyPlanner64** [comment] 2018-03-05 22:46
If you could upload one of the problematic boards, I could see if it has problems on 64drive.

Alternatively, [this was the board I tried](http://www.mariopartylegacy.com/forum/index.php?action=downloads;sa=view;down=101); if that doesn't work for you then that would also prove that the issue is specific to Everdrive for some reason.

Where specifically does it stop working? At the point when the spaces and board background are first seen?

**Comment by JMGO-N64** [comment] 2018-03-08 04:54
Yes, Precisely after the Millennium Star gives you 10 coins, them It crashs and gets a black screen!

**Comment by JMGO-N64** [comment] 2018-03-08 04:59
Tomorrow i will send some of my custom boards to you to test, let's Hope this helps to solve the ploblem!, By the way, thanks for all the support you are giving! :)

**Comment by JMGO-N64** [comment] 2018-03-08 05:01
I will test your board on my Everdrive to se If It Works.

**Comment by JMGO-N64** [comment] 2018-03-08 16:43
these is two of my mario party 3 cuatom boards:





[MP3 Custom Boards Json File.zip](https://github.com/PartyPlanner64/PartyPlanner64/files/1793961/MP3.Custom.Boards.Json.File.zip)

**Comment by PartyPlanner64** [comment] 2018-03-10 04:29
I was able to reproduce the black screen on 64drive. I'll have to do some brainstorming and figure what's different with these boards.

**Comment by JMGO-N64** [comment] 2018-03-15 18:12
I really do not know what causes this, but I'll do some research anyway, maybe I'll find something, Also Thank You for all the help you are giving! :)

**Comment by JMGO-N64** [comment] 2018-07-14 04:31
I've been playing your Custom board, Paradise Isles, it worked, but after some turns, a strange error ocurred, one of the computers have sent to a dead end, then when the Character tried to move, the crashed, i wonder what have caused that.

**Comment by PartyPlanner64** [comment] 2019-05-13 03:25
I tried the "Big Bounce n' Trounce" and "MP2 Rules Land" boards on real hardware again, and it appears that whatever issues they had, have been fixed. I don't know exactly what the problem was, but a lot of changes have been made over the past year.

If there are other boards that exhibit issues, please file a new issue with links to the boards. Closing this issue as fixed, thanks.

**Closed by PartyPlanner64** 2019-05-13 03:25 UTC
