### ISSUE TITLE
Unable to make it past turn 3

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [PartyPlanner64/PartyPlanner64#41] opened 2016-12-28 23:29 UTC
So I have tried like Yoshi and Mario and the crash as one thing in common everytime
The Turn number. By p1 3rd roll after the die is cast the game freezes. the music keeps playing etc. 
[Boards-Valentine Islands-v7.zip](https://github.com/PartyPlanner64/PartyPlanner64/files/676409/Boards-Valentine.Islands-v7.zip)

**Comment by P3rf3ctXZer0** [comment] 2016-12-28 23:30
![kkljl](https://cloud.githubusercontent.com/assets/10351221/21533731/5d72a264-cd23-11e6-9584-8fc6eaf7869e.png)

**Comment by P3rf3ctXZer0** [comment] 2016-12-28 23:31
The map goes over chilly waters.

**Comment by PartyPlanner64** [comment] 2017-01-03 01:48
Thanks for uploading it, not sure when I'll have time to look into it.

**Comment by PartyPlanner64** [comment] 2017-01-07 21:42
I played 4 or 5 turns and didn't observe any issues. Is there a specific emulator (or real hardware?) that is causing trouble?

**Comment by P3rf3ctXZer0** [comment] 2017-01-07 21:48
... I have no idea it was a damn nightmare to get it to run.

**Comment by P3rf3ctXZer0** [comment] 2017-01-07 21:48
what emu are you using?

**Comment by PartyPlanner64** [comment] 2017-01-07 21:55
Well I use Nemu64 (+ Rice Video plugin) because it has a debugger, but that is not very good for recreational purposes. Otherwise I use mupen64plus (command line) or just real hardware.

The most commonplace working setup is probably Project64 2.3 configured to use 8MB of RAM.

**Comment by P3rf3ctXZer0** [comment] 2017-01-07 22:14
Please use the latest PJ64

**Comment by P3rf3ctXZer0** [comment] 2017-01-07 22:14
Glide Plugin with basic settings.

**Comment by PartyPlanner64** [comment] 2019-05-13 03:28
Closing this issue due to age and low likelihood of reproducing the original issue. Many changes have been made to PP64 over the past couple of years and it's likely this issue has been fixed or will no longer manifest in the same way. Feel free to comment if the issue is still occurring, thanks.

**Closed by PartyPlanner64** 2019-05-13 03:28 UTC
Labels: crash, needs investigation
