### ISSUE TITLE
blank screen after opening cutscene

### ISSUE THREAD

**Issue by FB1rb** [PartyPlanner64/PartyPlanner64#119] opened 2021-06-20 05:21 UTC
after selecting everything (characters, difficulty, turn order) the game will show where the first star is, and then go blank. and the game never loads. i'm running this on mario party 2, on western land obviously. i've made a custom map before and it works completely fine to this day (and its less functional than this current map is, which makes no sense). i can provide whatever i need to provide i just dont know whats wrong.

i've tested different versions of pj64 to no avail, made sure ram is set to 8 gb and counter factor is 1, and nothing ever works.

**Comment by PartyPlanner64** [comment] 2021-06-26 17:08
Since it crashes just when the board loads, it sounds like a board-specific issue. I would need to be provided the board file (or link to a download) in order to assess further.

**Comment by PartyPlanner64** [comment] 2021-07-25 17:13
Closing this issue for now. If you provide a board that reproduces the issue we can reopen.

**Closed by PartyPlanner64** 2021-07-25 17:13 UTC
Labels: needs information
