### ISSUE TITLE
Spaces moving considerably after patching ROM

### ISSUE THREAD

**Issue by StalfosKing** [PartyPlanner64/PartyPlanner64#27] opened 2016-11-07 03:42 UTC
This is a consistent issue I've been having: I finish my space layout and click to patch the ROM. I then load up this new ROM and see if it patched correctly. When I look at my newly replaced board, I find that all spaces in approximately the top third of the board have been pushed down considerably. I then proceeded to combat this by moving the effected spaces up before patching a new ROM. I then test out THIS ROM in game, only to find that the spaces have been pushed downward and toward the edges of the screen depending on the side that they're closed to a CONSIDERABLY large distance. Please help.

**Comment by PartyPlanner64** [comment] 2016-11-07 03:54
Duplicate of issue #20, so closing. It is annoying to deal with, and it is also going to be unpleasant to fix.

**Closed by PartyPlanner64** 2016-11-07 03:54 UTC
Labels: duplicate
